<!-- Footer -->

<div id="siteInfo"> <img src="siteimages/spacer.gif" width="44" height="22" /> <a href="about.asp">About Us</a> | <a href="sitemap.html">Site Map</a> | <a href="privacy.asp">Privacy Policy</a> | <a href="contact.asp">Contact Us</a> | <img src="siteimages/spacer.gif" width="44" height="22" />&copy;1998 - 2006 Robert Moorehouse </div>
<br />
</div>
<!-- End Footer -->

<%
objConn1.close()
objConn2.close()
objConn3.close()
%>
</body>
</html>